#!/usr/bin/env bash

# make some symlinks for zsh themes
ln -sf $HOME/dotfiles/zsh/.oh-my-zsh/custom/themes/typewritten/typewritten.zsh-theme $HOME/dotfiles/zsh/.oh-my-zsh/custom/themes/typewritten.zsh-theme
ln -sf $HOME/dotfiles/zsh/.oh-my-zsh/custom/themes/typewritten/async $HOME/dotfiles/zsh/.oh-my-zsh/custom/themes/async


FOLDERS_LINUX=$(echo "bin nvim alacritty zsh tmux i3 polybar picom dunst rofi")
FOLDERS_MAC=$(echo "bin nvim zsh tmux")
FOLDER=$(echo "")

# remove .zshrc if it exists so we can
# create it with the correct version for the environment
if [ -f $HOME/dotfiles/zsh/.zshrc ]; then
	rm zsh/.zshrc
fi

case $1 in
	--macos )
		INSTALL_ENV="macos"
		FOLDERS=$FOLDERS_MAC
		cp $HOME/dotfiles/zsh/.zshrc_macos $HOME/dotfiles/zsh/.zshrc
		;;

	--linux )
		INSTALL_ENV="linux"
		FOLDERS=$FOLDERS_LINUX
		cp $HOME/dotfiles/zsh/.zshrc_linux $HOME/dotfiles/zsh/.zshrc
		;;

	* ) 
		echo -e "Please specify which environment to install:\n--linux\n--macos"
		exit
	;;
esac

echo "Installing for env: $INSTALL_ENV"
for folder in $FOLDERS
do
	echo "Installing $folder"
	stow -D $folder
	stow $folder
done
