#!/usr/bin/env bash

DOTFILES_FOLDER="$HOME/dotfiles"
FOLDERS_LINUX=$(echo "bin nvim alacritty bash tmux i3 polybar fontconfig starship")
FOLDERS_I3=$(echo "i3 polybar dunst rofi picom")
FOLDERS_MAC=$(echo "bin alacritty nvim zsh tmux gnupg-mac starship")
FOLDERS=$(echo "")

# remove .zshrc if it exists so we can
# create it with the correct version for the environment
if [ -f $DOTFILES_FOLDER/bash/.bashrc ]; then
	rm $DOTFILES_FOLDER/bash/.bashrc
fi

# remove alacritty config if it exists so we can
# create it with the correct version for the environment
if [ -f $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty.toml ]; then
	rm $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty.toml
fi

# remove kitty config if it exists so we can
# create it with the correct version for the environment
if [ -f $DOTFILES_FOLDER/kitty/.config/kitty/kitty.conf ]; then
	rm $DOTFILES_FOLDER/kitty/.config/kitty/kitty.conf
fi

case $1 in
	--macos )
		INSTALL_ENV="macos"
		FOLDERS=$FOLDERS_MAC
		cp $DOTFILES_FOLDER/bash/.bashrc_macos $HOME/dotfiles/bash/.bashrc
		cp $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty_macos.toml $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty.toml
		cp $DOTFILES_FOLDER/kitty/.config/kitty/kitty_macos.conf $DOTFILES_FOLDER/kitty/.config/kitty/kitty.conf
		;;

	--linux )
		INSTALL_ENV="linux"
		FOLDERS=$FOLDERS_LINUX
		cp $DOTFILES_FOLDER/bash/.bashrc_linux $DOTFILES_FOLDER/bash/.bashrc
		cp $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty_linux.toml $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty.toml
		cp $DOTFILES_FOLDER/kitty/.config/kitty/kitty_linux.conf $DOTFILES_FOLDER/kitty/.config/kitty/kitty.conf
		;;
	--i3 )
		INSTALL_ENV="I3"
		FOLDERS=$FOLDERS_I3
		cp $DOTFILES_FOLDER/bash/.bashrc_linux $DOTFILES_FOLDER/bash/.bashrc
		cp $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty_linux.toml $DOTFILES_FOLDER/alacritty/.config/alacritty/alacritty.toml
		;;

	* ) 
		echo -e "Please specify which environment to install:\n--linux\n--macos"
		exit
	;;
esac

echo "Installing for env: $INSTALL_ENV"
for folder in $FOLDERS
do
	echo "Installing $folder"
	stow -D $folder
	stow $folder
done
